from collections.abc import Sequence
from os import PathLike
from typing import final
class BpeTrainerBase: ...

@final
class BpeTrainer_Character_CharIdx(BpeTrainerBase):
    def __new__(cls, /, special_tokens: Sequence[str]) -> BpeTrainer_Character_CharIdx: ...
    def add_words(self, /, words: Sequence[tuple[str, int]]) -> None: ...
    def init_training(self, /) -> None: ...
    def save_merges_txt(self, /, path: str | PathLike, spec: str) -> None: ...
    def save_vocab(self, /, path: str | PathLike, spec: str) -> None: ...
    def step(self, /) -> None: ...
    def vocab_size(self, /) -> int: ...

@final
class BpeTrainer_u8_Idx(BpeTrainerBase):
    def __new__(cls, /, special_tokens: Sequence[str]) -> BpeTrainer_u8_Idx: ...
    def add_words(self, /, words: Sequence[tuple[str, int]]) -> None: ...
    def init_training(self, /) -> None: ...
    def save_merges_txt(self, /, path: str | PathLike, spec: str) -> None: ...
    def save_vocab(self, /, path: str | PathLike, spec: str) -> None: ...
    def step(self, /) -> None: ...
    def vocab_size(self, /) -> int: ...
